{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rabbitmq.name" . }}-allow
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
      ports:
        - port: 5672
          protocol: TCP
        - port: 4369
          protocol: TCP
        - port: 25672
          protocol: TCP
        - port: 15672
          protocol: TCP
  {{- range .Values.ciliumNetworkPolicy.allowed_labels }}
    - from:
        - podSelector:
            matchLabels:
               {{- toYaml .matchLabels | nindent 14 }}    
      ports:
        - port: 5672
          protocol: TCP
  {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
      ports:
        - port: 5672
          protocol: TCP
        - port: 4369
          protocol: TCP
        - port: 25672
          protocol: TCP
        - port: 15672
          protocol: TCP

{{- end }}
