{{- if .Values.KyvernoPolicyException.enabled }}
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
    helm.sh/chart: {{ include "rabbitmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
spec:
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - StatefulSet
        namespaces:
        - {{ .Release.Namespace }}
        names:
        - {{ include "rabbitmq.name" . }}*
  exceptions:
  {{- range .Values.KyvernoPolicyException.exceptions }}
  - policyName: {{ .policyName }}
    ruleNames:
    {{- range .ruleNames }}
    - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}